part 3 done

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,6 +3,7 @@ default:
 
 stages:
   - build
+  - code_style
 
 build_job:
   stage: build
@@ -16,5 +17,21 @@ build_job:
     paths:
       - artifacts
     expire_in: 30 days
+  only:
+    - develop
+
+clang_format_job:
+  stage: code_style
+  script:
+    - cp materials/linters/.clang-format src/cat/
+    - cp materials/linters/.clang-format src/grep/
+    - echo "Running clang-format check..."
+    - |
+      if clang-format -n --Werror --verbose src/cat/*.c src/grep/*.c; then
+        echo "Clang-format check passed."
+      else
+        echo "clang-format check failed."
+        exit 1
+      fi
   only:
     - develop
